public class Main{
    public static void main(String[] args){
        listOfBooks l1 = new listOfBooks();
        l1.addBook("Razboiul care m-a invatat sa traiesc", 335,4.5,"History","Ada lupta cu sine pentru a accepta sensul nou pe care il capata pentru ea cuvantul familie, dar lupta si cu propria identitate, " + "demonstrand ca adevarata libertate nu este reprezentata doar de posibilitatea de a alege, ci de a face alegerea corecta. Odata ce descopera ca frica nu exclude curajul, devine invincibila si isi aduna puterile pentru a le aduce speranta celor din jur, ba chiar si pilotilor din al Doilea Razboi Mondial");
        l1.addBook("Universul Stie",195, 4.0,"History","Cand Virgil s-a trezit in acea dimineata de vara, habar n-avea prin ce urma sa treaca. A plecat grabit spre casa lui Kaori Tanaka, prietena lui cititoare-n stele, si, ca de obicei, a luat-o prin padure. Stia drumul, stia padurea, ce nu stia era ca fix in acea zi avea sa se intalneasca cu cel mai mare bully din scoala. Si ce nu mai stia era ca fata de care ii placea, Valencia, se indrepta si ea spre Kaori, luand-o prin aceeasi padure. Sa fie totul o simpla coincidenta sau unele lucruri sunt menite sa se intample?Protagonistii indrazneti si povestea iscusita vor fi pe placul tuturor celor care s-au simtit la un moment dat putin pierduti in univers. Cititorii vor fi imediat atrasi de romanul acesta, care are ceva pentru fiecare: umor, acceptare de sine, familie si un sfarsit profetic.");
        l1.addBook("Minti Geniale", 273, 3.5,"Adventure","Eli Frieden locuieste in singurul oras perfect din lume: Serenity din New Mexico, SUA. Toata lumea are o casa mare, cu piscina. Nu exista probleme financiare, nici infractiuni. Onestitatea si integritatea sunt valorile principale. Cei treizeci de copii care traiesc aici nu mint niciodata. Stiu ca e o cale scurta de la minciuna la problemele inspaimantatoare din alte locuri, mai putin norocoase.Eli n-a iesit niciodata din Serenity... pana intr-o zi cand depaseste cu bicicleta granita lui. Atunci se intampla ceva atat de neasteptat si nebunesc, incat viata ii este complet data peste cap.");
        l1.addBook("Razboiul care mi-a salvat viata", 287, 4.0,"History","Ada, o fetiţă de nouă ani, are de purtat propria ei bătălie pentru a demonstra că nu e cu nimic diferită de ceilalţi.Umilită de propria mamă din cauza unui defect fizic, ţinută captivă în apartamentul lor cu o singură cameră, Ada profită de faptul că toţi copiii sunt evacuaţi din Londra şi, împreună cu fratele ei, Jamie, fuge departe de răutatea mamei. Aşa ajung să o cunoască pe Susan Smith, o femeie posacă, dar care îi iubește ca şi cum ar fi copiii ei. Și, în timp ce lumea întreagă se schimbă și toți cei din jur cunosc suferinţa şi despărţirea, Ada descoperă ce înseamnă iubirea şi respectul.");
        l1.addBook("Fratii Willoughby", 145, 2.0, "Adventure", " Frații Willoughby sunt copii de modă veche care adoră aventurile de modă veche. Din păcate, domnul și doamna Willoughby nu sunt foarte încântați de fiii și fiica lor. Ba mai mult, uneori uită că sunt părinți și urăsc când cineva le amintește asta. Inspirați de un basm clasic, ei se gândesc cum să scape de copiii lor. Dar ăsta nu-i un motiv de îngrijorare pentru cei patru frați dornici de aventură, căci și ei au ticluit un plan prin care să devină liberi.Și-atunci când descoperă în pragul casei lor înguste și lunguiețe un bebeluș abandonat, copiii nu au de unde să știe că este abia începutul unor întâmplări din care n-o să lipsească umorul, inteligența și curajul fără limite.");
        l1.addBook("din 7 in 7", 348, 4.5, "Smart", "Willow Chance e o fetiță de doisprezece ani cu o minte de geniu, obsedată de natură și de stabilirea diagnosticelor medicale. Dacă e agitată, se liniștește numărând din 7 în 7. Nu i-a fost niciodată ușor să lege prietenii, iar cei mai apropiați oameni sunt chiar părinții ei adoptivi.Din 7 în 7 este o carte emoționantă despre cum e să fii diferit, despre cum se poate face față unei imense pierderi, despre ce înseamnă cu adevărat o familie.");
        l1.addBook("Ca pestele in copac", 253, 4.5, "Smart", "Ally e in clasa a sasea si a invatat, in cele sapte scoli prin care a trecut, ca cel mai important e sa taca si sa treaca neobservata. Ii place sa deseneze si sa rezolve probleme de matematica – din cele cu putine cuvinte, pentru ca literele se misca intruna.Ar vrea sa spuna adevarul si sa ceara ajutor, dar ii e teama ca toata lumea o considera deja o pacoste. Insa domnul Daniels, noul ei profesor, reuseste sa-i vada potentialul si o ajuta sa nu se mai teama de litere sau de citit. Datorita lui si bunilor ei prieteni, ajunge sa nu se mai simta ca un peste in copac si accepta faptul ca a fi diferit nu e deloc ceva rau.");
        l1.addBook("Elias si spioana Carturarilor I",500, 4.5, "Adventure", "Elias este cel mai bun soldat al Academiei militare a Imperiului – si, in secret, cel care isi doreste cel mai putin sa se afle acolo. Aflat pe punctul de a dezerta, se vede obligat sa participe la o competitie nemiloasa al carei castigator va fi desemnat imparat. Laia face parte din clanul Carturarilor, inrobit de multi ani de catre Razboinici. Cand fratele ei este arestat sub acuzatia de tradare, Laia ia legatura cu miscarea de rezistenta impotriva asupritorilor, in speranta ca ii vor elibera fratele. In schimbul ajutorului, rebelii ii cer sa se strecoare in Academie si sa spioneze pentru ei. Cand Elias si Laia se intalnesc, isi vor da seama ca legatura dintre ei este mult mai puternica decat ar fi crezut vreodata si ca soarta Imperiului se afla in mainile lor. Destinele li se incruciseaza intr-o poveste care se citeste cu sufletul la gura, despre curaj, iubire, loialitate si libertate, intr-o lume in care totul le este potrivnic");
        l1.addBook("Elias si spioana Carturarilor II", 497, 4.0, "Adventure", "Elias si Laia fug ca sa scape cu viata. Soldatii sunt pe urmele lor in timp ce parasesc Serra si se indreapta spre adancurile Imperiului. Laia e hotarata sa patrunda in Inchisoarea Kauf, cea mai temuta temnita din tinut, ca sa-si salveze fratele din mainile caruia sta salvarea Carturarilor. Elias e hotarat s-o ajute pe Laia, chiar daca asta ar insemna s-o faca cu ultimele lui puteri. Dar forte intunecate, umane sau venite din alte sfere, li se impotrivesc. Cei doi trebuie sa fie mereu cu-n pas inaintea inamicilor: cruntul Comandant, sangerosul Imparat Marcus, sadicul Gardian-sef al inchisorii sau, vai!, Helene Aquilla, buna prietena a lui Elias, care are de dus la capat o misiune teribila in noul ei rol de mare Sfrancioc al Imperiului: sa-i gaseasca pe tradatorul Elias Veturius si pe sclava Carturareasa care l-a ajutat sa scape si... sa-i omoare pe amandoi.");


        //Tests For The Code:
        l1.getByTitle("din 7 in 7");
        l1.getByRating(2.5);
        l1.getTitlesOfBooks();
        l1.getPages();
        l1.getListOfBooks();
        l1.getNumberOfBooks();

        listOfBooks l2 = new listOfBooks();
        l2.addBook("Test Book", 105, 3.0, "Drama", "Test Description");
        l2.addBook("Test Book#2", 115, 2.0, "Drama", "Test Description");


    }
}